<?php 

//Codigos en PHP para SUMAR-RESTAR-MULTIPLICAR-DIVIDIR

$numero1=55;
$numero2=11;


$suma=$numero1+$numero2;
$resta=$numero1-$numero2;
$multiplicacion=$numero1*$numero2;
$division=$numero1/$numero2;


echo("................");
echo("<br>");
echo("la suma es");
echo("<br>");
echo($suma);
echo("<br>");
echo("la resta es");
echo("<br>");
echo($resta);
echo("<br>");
echo("la multiplicacion es");
echo("<br>");
echo($multiplicacion);
echo("<br>");
echo("la divisicion es");
echo("<br>");
echo($division);









?>
